//
// Created by vince on 06.04.21.
//

#include "RawPacket.h"

RawPacket::RawPacket(PacketType type,
                     unsigned char specificFlags,
                     unsigned int length,
                     char *data) :
        _type(type),
        _specific_flags(specificFlags),
        _length(length),
        _data(data) {}
// should be autogenerated
//RawPacket::RawPacket(RawPacket const& p)